
baseurl: "/public-health-map-germany"

title: Public health map
author: Jakob Schumacher
email: jakob.schumacher@web.de
description: > # this means to ignore newlines until "show_exerpts:"
  Eine Karte von Public Health Playern in Germany

